// Code generated by protoc-gen-go. DO NOT EDIT.
// source: karyawan.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	karyawan.proto

It has these top-level messages:
	AddKaryawanReq
	ReadKaryawanByNamaReq
	ReadKaryawanByNamaResp
	ReadKaryawanResp
	UpdateKaryawanReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddKaryawanReq struct {
	NamaKaryawan string `protobuf:"bytes,1,opt,name=NamaKaryawan" json:"NamaKaryawan,omitempty"`
	IdAgama      int32  `protobuf:"varint,2,opt,name=IdAgama" json:"IdAgama,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=Alamat" json:"Alamat,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=JenisKelamin" json:"JenisKelamin,omitempty"`
	Status       int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreateBy     string `protobuf:"bytes,6,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *AddKaryawanReq) Reset()                    { *m = AddKaryawanReq{} }
func (m *AddKaryawanReq) String() string            { return proto.CompactTextString(m) }
func (*AddKaryawanReq) ProtoMessage()               {}
func (*AddKaryawanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddKaryawanReq) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *AddKaryawanReq) GetIdAgama() int32 {
	if m != nil {
		return m.IdAgama
	}
	return 0
}

func (m *AddKaryawanReq) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *AddKaryawanReq) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *AddKaryawanReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddKaryawanReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadKaryawanByNamaReq struct {
	NamaKaryawan string `protobuf:"bytes,1,opt,name=NamaKaryawan" json:"NamaKaryawan,omitempty"`
}

func (m *ReadKaryawanByNamaReq) Reset()                    { *m = ReadKaryawanByNamaReq{} }
func (m *ReadKaryawanByNamaReq) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByNamaReq) ProtoMessage()               {}
func (*ReadKaryawanByNamaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadKaryawanByNamaReq) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

type ReadKaryawanByNamaResp struct {
	NamaKaryawan string `protobuf:"bytes,1,opt,name=NamaKaryawan" json:"NamaKaryawan,omitempty"`
	IdAgama      int32  `protobuf:"varint,2,opt,name=IdAgama" json:"IdAgama,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=Alamat" json:"Alamat,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=JenisKelamin" json:"JenisKelamin,omitempty"`
	Status       int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreateBy     string `protobuf:"bytes,6,opt,name=CreateBy" json:"CreateBy,omitempty"`
}

func (m *ReadKaryawanByNamaResp) Reset()                    { *m = ReadKaryawanByNamaResp{} }
func (m *ReadKaryawanByNamaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanByNamaResp) ProtoMessage()               {}
func (*ReadKaryawanByNamaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadKaryawanByNamaResp) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetIdAgama() int32 {
	if m != nil {
		return m.IdAgama
	}
	return 0
}

func (m *ReadKaryawanByNamaResp) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *ReadKaryawanByNamaResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadKaryawanByNamaResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

type ReadKaryawanResp struct {
	AllKaryawan []*ReadKaryawanByNamaResp `protobuf:"bytes,1,rep,name=allKaryawan" json:"allKaryawan,omitempty"`
}

func (m *ReadKaryawanResp) Reset()                    { *m = ReadKaryawanResp{} }
func (m *ReadKaryawanResp) String() string            { return proto.CompactTextString(m) }
func (*ReadKaryawanResp) ProtoMessage()               {}
func (*ReadKaryawanResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadKaryawanResp) GetAllKaryawan() []*ReadKaryawanByNamaResp {
	if m != nil {
		return m.AllKaryawan
	}
	return nil
}

type UpdateKaryawanReq struct {
	NamaKaryawan string `protobuf:"bytes,1,opt,name=NamaKaryawan" json:"NamaKaryawan,omitempty"`
	IdAgama      int32  `protobuf:"varint,2,opt,name=IdAgama" json:"IdAgama,omitempty"`
	Alamat       string `protobuf:"bytes,3,opt,name=Alamat" json:"Alamat,omitempty"`
	JenisKelamin string `protobuf:"bytes,4,opt,name=JenisKelamin" json:"JenisKelamin,omitempty"`
	Status       int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	UpdateBy     string `protobuf:"bytes,6,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
}

func (m *UpdateKaryawanReq) Reset()                    { *m = UpdateKaryawanReq{} }
func (m *UpdateKaryawanReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateKaryawanReq) ProtoMessage()               {}
func (*UpdateKaryawanReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateKaryawanReq) GetNamaKaryawan() string {
	if m != nil {
		return m.NamaKaryawan
	}
	return ""
}

func (m *UpdateKaryawanReq) GetIdAgama() int32 {
	if m != nil {
		return m.IdAgama
	}
	return 0
}

func (m *UpdateKaryawanReq) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *UpdateKaryawanReq) GetJenisKelamin() string {
	if m != nil {
		return m.JenisKelamin
	}
	return ""
}

func (m *UpdateKaryawanReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateKaryawanReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddKaryawanReq)(nil), "grpc.AddKaryawanReq")
	proto.RegisterType((*ReadKaryawanByNamaReq)(nil), "grpc.ReadKaryawanByNamaReq")
	proto.RegisterType((*ReadKaryawanByNamaResp)(nil), "grpc.ReadKaryawanByNamaResp")
	proto.RegisterType((*ReadKaryawanResp)(nil), "grpc.ReadKaryawanResp")
	proto.RegisterType((*UpdateKaryawanReq)(nil), "grpc.UpdateKaryawanReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for KaryawanService service

type KaryawanServiceClient interface {
	AddKaryawan(ctx context.Context, in *AddKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadKaryawanByNama(ctx context.Context, in *ReadKaryawanByNamaReq, opts ...grpc1.CallOption) (*ReadKaryawanByNamaResp, error)
	ReadKaryawan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKaryawanResp, error)
	UpdateKaryawan(ctx context.Context, in *UpdateKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type karyawanServiceClient struct {
	cc *grpc1.ClientConn
}

func NewKaryawanServiceClient(cc *grpc1.ClientConn) KaryawanServiceClient {
	return &karyawanServiceClient{cc}
}

func (c *karyawanServiceClient) AddKaryawan(ctx context.Context, in *AddKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/AddKaryawan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) ReadKaryawanByNama(ctx context.Context, in *ReadKaryawanByNamaReq, opts ...grpc1.CallOption) (*ReadKaryawanByNamaResp, error) {
	out := new(ReadKaryawanByNamaResp)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/ReadKaryawanByNama", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) ReadKaryawan(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadKaryawanResp, error) {
	out := new(ReadKaryawanResp)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/ReadKaryawan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *karyawanServiceClient) UpdateKaryawan(ctx context.Context, in *UpdateKaryawanReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.KaryawanService/UpdateKaryawan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KaryawanService service

type KaryawanServiceServer interface {
	AddKaryawan(context.Context, *AddKaryawanReq) (*google_protobuf.Empty, error)
	ReadKaryawanByNama(context.Context, *ReadKaryawanByNamaReq) (*ReadKaryawanByNamaResp, error)
	ReadKaryawan(context.Context, *google_protobuf.Empty) (*ReadKaryawanResp, error)
	UpdateKaryawan(context.Context, *UpdateKaryawanReq) (*google_protobuf.Empty, error)
}

func RegisterKaryawanServiceServer(s *grpc1.Server, srv KaryawanServiceServer) {
	s.RegisterService(&_KaryawanService_serviceDesc, srv)
}

func _KaryawanService_AddKaryawan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddKaryawanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).AddKaryawan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/AddKaryawan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).AddKaryawan(ctx, req.(*AddKaryawanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_ReadKaryawanByNama_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadKaryawanByNamaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).ReadKaryawanByNama(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/ReadKaryawanByNama",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).ReadKaryawanByNama(ctx, req.(*ReadKaryawanByNamaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_ReadKaryawan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).ReadKaryawan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/ReadKaryawan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).ReadKaryawan(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KaryawanService_UpdateKaryawan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKaryawanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KaryawanServiceServer).UpdateKaryawan(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.KaryawanService/UpdateKaryawan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KaryawanServiceServer).UpdateKaryawan(ctx, req.(*UpdateKaryawanReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _KaryawanService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.KaryawanService",
	HandlerType: (*KaryawanServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddKaryawan",
			Handler:    _KaryawanService_AddKaryawan_Handler,
		},
		{
			MethodName: "ReadKaryawanByNama",
			Handler:    _KaryawanService_ReadKaryawanByNama_Handler,
		},
		{
			MethodName: "ReadKaryawan",
			Handler:    _KaryawanService_ReadKaryawan_Handler,
		},
		{
			MethodName: "UpdateKaryawan",
			Handler:    _KaryawanService_UpdateKaryawan_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "karyawan.proto",
}

func init() { proto.RegisterFile("karyawan.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x14, 0xa4, 0x7c, 0xa9, 0x0f, 0x82, 0xfa, 0xa2, 0xb8, 0x29, 0x1e, 0xc8, 0x9e, 0x38, 0x95, 0x04,
	0x8f, 0x46, 0x23, 0x10, 0x0f, 0x4a, 0x62, 0x62, 0x89, 0x3f, 0xe0, 0x41, 0xd7, 0x86, 0xd8, 0xd2,
	0x52, 0x16, 0x4d, 0xff, 0x92, 0x3f, 0xc2, 0xc4, 0x8b, 0xbf, 0xcb, 0xf4, 0x0b, 0x17, 0x01, 0xe3,
	0x51, 0x8f, 0x33, 0xdd, 0x99, 0xbe, 0x99, 0xdd, 0x07, 0xb5, 0x27, 0x0a, 0x42, 0x7a, 0xa1, 0xa9,
	0xe1, 0x07, 0x9e, 0xf4, 0xb0, 0x68, 0x07, 0xfe, 0x58, 0x6f, 0xd8, 0x9e, 0x67, 0x3b, 0xa2, 0x1d,
	0x73, 0xa3, 0xc5, 0x63, 0x5b, 0xb8, 0xbe, 0x0c, 0x93, 0x23, 0xfc, 0x4d, 0x83, 0x5a, 0xd7, 0xb2,
	0x06, 0xa9, 0xd0, 0x14, 0x33, 0xe4, 0x50, 0xbd, 0x23, 0x97, 0x32, 0x8a, 0x69, 0x4d, 0xad, 0xb5,
	0x67, 0xae, 0x70, 0xc8, 0x60, 0xe7, 0xc6, 0xea, 0xda, 0xe4, 0x12, 0xcb, 0x37, 0xb5, 0x56, 0xc9,
	0xcc, 0x20, 0xd6, 0xa1, 0xdc, 0x75, 0xc8, 0x25, 0xc9, 0x0a, 0xb1, 0x2e, 0x45, 0x91, 0xeb, 0xad,
	0x98, 0x4e, 0xe6, 0x03, 0xe1, 0x90, 0x3b, 0x99, 0xb2, 0x62, 0xe2, 0xaa, 0x72, 0x91, 0x76, 0x28,
	0x49, 0x2e, 0xe6, 0xac, 0x14, 0x9b, 0xa6, 0x08, 0x75, 0xd8, 0xed, 0x07, 0x82, 0xa4, 0xe8, 0x85,
	0xac, 0x1c, 0xeb, 0x96, 0x98, 0x9f, 0xc3, 0xb1, 0x29, 0x68, 0x19, 0xa0, 0x17, 0x46, 0x73, 0xfe,
	0x32, 0x06, 0xff, 0xd0, 0xa0, 0xbe, 0x49, 0x3d, 0xf7, 0xff, 0x59, 0x0b, 0x26, 0x1c, 0xa8, 0x39,
	0xe2, 0x04, 0x97, 0x50, 0x21, 0xc7, 0x51, 0x02, 0x14, 0x5a, 0x95, 0xce, 0xa9, 0x11, 0xbd, 0x09,
	0x63, 0x73, 0x68, 0x53, 0x15, 0xf0, 0x77, 0x0d, 0x0e, 0x1f, 0x7c, 0x8b, 0xa4, 0xf8, 0xf3, 0xaf,
	0x23, 0x19, 0xf3, 0xab, 0x97, 0x0c, 0x77, 0x5e, 0xf3, 0xb0, 0x9f, 0x8d, 0x35, 0x14, 0xc1, 0xf3,
	0x64, 0x2c, 0xf0, 0x02, 0x2a, 0xca, 0x8b, 0xc7, 0xa3, 0xa4, 0x91, 0xd5, 0x25, 0xd0, 0xeb, 0x46,
	0xb2, 0x35, 0x46, 0xb6, 0x35, 0xc6, 0x75, 0xb4, 0x35, 0x3c, 0x87, 0xf7, 0x80, 0xeb, 0xed, 0x61,
	0x63, 0x7b, 0xaf, 0x33, 0xfd, 0xc7, 0xd2, 0x79, 0x0e, 0xaf, 0xa0, 0xaa, 0x7e, 0xc3, 0x2d, 0x3f,
	0x8f, 0x86, 0xfa, 0xee, 0x93, 0x3a, 0xf4, 0xa1, 0xb6, 0x7a, 0x55, 0x78, 0x92, 0x9c, 0x5d, 0xbb,
	0xc0, 0xed, 0xc9, 0x46, 0xe5, 0x98, 0x39, 0xfb, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x42, 0xf2, 0x5e,
	0x43, 0x47, 0x04, 0x00, 0x00,
}
